### ISSUE TITLE
It works, thank you!!!!

### ISSUE THREAD

**Issue by helgek** [M4GNV5/esphome-SK20-Nebula-Light#3]
Dear Jakob,

I just successfully flashed my SK20 and ordered a second immediately to have one more in the living room. I had it in my house since 2 years and doing the ESP replacement exercise had been on my medium-term to-do list. Now this is obsolete! With the successful jailbreak almost all of my devices in my smart home (about 80 devices in total, most of them Zigbee) are now cloud independent which is a great situation. My previous flashing experience was with several Yeelight lamps which now also run on ESPHome and luckily for them I found a solution to access the ESP pins without soldering by using an amazing product called PCBite from a Swedish company (otherwise I would have had to give up on these ESP chips because they were barely accessible due to the board design). The only remaining cloud dependent devices are (and will remain to be) my car, my dishwasher and my washing machine, something I can certainly live with :D

Thank you for your great contribution!!

Helge

PS: Would you mind if more people become aware of your solution, like mentions in forums, etc.? I only found your project through some more extensive research, almost all search efforts still pointed to the WB3S chip replacement solutions.

**Comment by M4GNV5** [comment]
Thanks for the very nice message.
Feel free to mention this project anywhere you like (social media, blog posts, etc.).
I would love to see them, so please link posts them here!

I will close this issue, but you should still be able to add links afterwards

**Comment by helgek** [comment]
I left a few posts in some threads which were dealing with this projector to guide people to your project + I left a review where I had initially bought the projector (and some additional sellers of the same device pending review):

- https://www.amazon.de/-/en/gp/customer-reviews/R26S1LSEY6BB41/ref=cm_cr_arp_d_rvw_ttl?ie=UTF8&ASIN=B08VGK1V82

- https://community.home-assistant.io/t/tuya-smart-galaxy-projector/354691/18?u=helge_k
- https://community.home-assistant.io/t/how-do-i-change-nebula-color-on-tuya-star-projector/336126/9
