### ISSUE TITLE
Error binary size: Unknown error from ESP

### ISSUE THREAD

**Issue by tehniemer** [M4GNV5/esphome-SK20-Nebula-Light#5]
I'm getting this error trying to OTA flash from the ESPHome dashboard, have you seen this or have any suggestions on what to try to resolve it? 

edit:
However, I can OTA flash the `.uf2` file using the device's webserver.

**Comment by M4GNV5** [comment]
Maybe "esphome dashboard" (I assume in homeassistant?) uses another flash procedure. The error message also looks wrong: The chip in use is no ESP32/ESP8266, its a BK7231T.
Are there any flash options in the dashboard? Maybe you can make it use the working .uf2 procedure.

**Comment by tehniemer** [comment]
I have a standalone dashboard since I run home assistant in docker, but essentially yes, it's the same thing.

Oddly enough, I tried OTA flashing again this morning from esphome to get the error that was logged on the device, but it worked... Closing this for now. Thanks for the response and development work on this.
