### ISSUE TITLE
Latest esphome requires changes to recommended_base.yaml

### ISSUE THREAD

**Issue by matellis** [M4GNV5/esphome-SK20-Nebula-Light#6]
I think this is one of the breaking changes in the latest esphome, I ran into it on Home Assistant for other esp32 devices before I tried to do this.

Following the instructions, I get this:
```
$ esphome compile recommended_base.yaml
INFO Reading configuration recommended_base.yaml...
Failed config

esphome: [source recommended_base.yaml:5]

  Platform missing. You must include one of the available platform keys: esp32, esp8266.
  name: nebula
```
So I add `platform: esp32` or `platform: esp8266` to the file, and get this:
```
$ esphome compile recommended_base.yaml
INFO Reading configuration recommended_base.yaml...
Failed config

esp8266: None

  'board' is a required option for [esp8266].
  {}
```
If I add `board=wb3s` to the file underneath platform, I get this:
```
$ esphome compile recommended_base.yaml
INFO Reading configuration recommended_base.yaml...
Failed config

esp8266: None

  This board is unknown, please set the variant manually.
  board: wb3s
```
Looking up board types from [this list](https://registry.platformio.org/platforms/platformio/espressif32/boards) I can't find a wb3s or even the sk12 that the [hardware change](https://github.com/kireque/esphome_nebula_light#tuya-wb3s) approach refers to.

Running Python 3.8.10 and Esphome 2022.9.4

Any thoughts?

**Comment by matellis** [comment]
I think this is down to an out of date version of esphome. Closing this until I can make sure it's not that.

**Comment by matellis** [comment]
OK, for current version 2024.6.4 or later, there is a breaking change required as per the [release notes](https://esphome.io/changelog/2024.6.0.html) for this version.

The following section:
```
logger:
  level: INFO

ota:
  password: !secret ota_password

web_server:
  port: 80
```
Needs to be changed to:
```
logger:
  level: INFO

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  port: 80
```
Note the extra line under the `ota` section. Then everything proceeds. I'll try to do a PR for this.

**Comment by M4GNV5** [comment]
Thank you for the PR, its merged.

So the original error about the missing plattform was because of an outdated esphome version you were running?
I assume we can close this issue now

Have fun using your nebula :wink:
