### ISSUE TITLE
SK20 does not support AP mode on firmware 2.0.2

### ISSUE THREAD

**Issue by danishru** [M4GNV5/esphome-SK20-Nebula-Light#8]
I just got a brand new SK20 star projector. I had everything ready and was ready to flash it, but no matter what I tried I couldn't get it to go into access point mode. If I hold the power button, the projector switches to EZ mode and quickly blinks blue, and no action can get it to blink slowly to start AP mode. I suspect that Tuya has disabled this mode completely for new firmware. My projector has firmware version 2.0.2 for the main module and microcontroller.

Maybe there is some secret way to enable AP mode? I really don't want to reflash it via USB-TTL.

**Comment by danishru** [comment]
I opened it. My copy has a [CBU chip](https://developer.tuya.com/en/docs/iot/cbu-module-datasheet?id=Ka07pykl5dk4u).

It is based on the BK7231N microcontroller, so it turns out that I can't flash it using your method, even if I run the projector in AP mode?

A quick search showed that the [pinout of the CBU](https://docs.libretiny.eu/boards/cbu/#pin-functions) chip for controlling projectors is the same as that of the [WB3S chip](https://docs.libretiny.eu/boards/wb3s/#pin-functions). Do I understand correctly that if I specify in the ESPHome YAML configuration

```
bk72xx:
  board: cbu
```

then everything should work without changing the rest of the code? And will it be possible to flash over the air, if the firmware is ultimately vulnerable to the Tuya Cloudcutter vulnerability? The question then is how to enable AP mode in the projector on the CBU chip?

Here are photos of the board and the projector label. Maybe someone will find it useful.
![IMG_1056](https://github.com/user-attachments/assets/8d2b87c9-e761-47c0-a741-605b8770cba8)
![IMG_1057](https://github.com/user-attachments/assets/b24a2e8d-150b-4ca2-8464-c13007db08d1)

**Comment by M4GNV5** [comment]
What is "EZ mode"? I never used the device with its original firmware, but there must be some way for the device to be configured to connect to your wifi.
Often this is done by creating a wifi access point, but if you are unlucky it might use bluetooth, since the CBU chip supports it.

What does the manual say regarding factory resetting / connecting to a new wifi?

Since you have already opened your SK20, you could also try flashing the uC directly by connecting wires to the daughterboard.

**Comment by danishru** [comment]
> What is "EZ mode"?

As far as I understand, Tuya has several device configuration modes. In particular, for devices with WiFi, there are ["EZ mode" and "AP mode"](https://support.tuya.com/en/help/_detail/K9hut3pgw8va5).

> What does the manual say regarding factory resetting / connecting to a new wifi?

The manual specifies two connection modes using ["Bluetooth Mode Configuration (Common)" and "Quick Mode Configuration"](https://manualspro.net/470058-shenzhen-nanxin-technology-sk20-smart-star-projector-user-manual), which is exactly "EZ mode". There is no "AP mode".

Yes, I'm already studying how to flash it with wires. If it works out, I'll also post a dump of the new firmware in issue tuya-cloudcutter.

You probably need to add a mention that the new SK20 have a different chip, and if the firmware is 2.0.2, then flashing it over the air in your way is currently not possible, since there is no information on how to start the "AP mode".

**Comment by M4GNV5** [comment]
Reading the updates in https://github.com/tuya-cloudcutter/tuya-cloudcutter/issues/731 I assume we can close this issue here.
Very good reverse pictures, engineering work and documentation. Nicely done!

For future persons having the SK20 with version 2.0.2: Try pressing the power button 10 times or for 10 seconds.

**Comment by Flumeded** [comment]
@M4GNV5 I published esphome configuration file for CBU based starlight projectors -- https://github.com/Flumeded/esphome-SK23-Nebula-Light

I can create a pull request into the readme that mentiones that if you running such device, you need to use another yml file


Or we can consider merging both ymls into your project 

@danishru already confirmed that their CBU-based SK20 uses the same pinout as in mine repository

**Comment by danishru** [comment]
> For future persons having the SK20 with version 2.0.2: Try pressing the power button 10 times or for 10 seconds.

Pressing for 10 seconds definitely does not put the device into access point mode. 
And I can no longer test 10 power-off cycles, but it would be great if someone in the future could test this.

**Comment by f45tb00t** [comment]
Hi. 

Not sure which version I precisely have. I had some struggle to get it into AP mode. But finally it worked.

for me it was
- 7 seconds button press, then the light flashed shortly up and the LED blinked fast. 
- 7 seconds button press, the light came up again and the LED started blinking slowly.

But for flashing I used the information I got from M4GNV5
